# Generated by Django 5.1.6 on 2025-02-14 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Planet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("distance", models.FloatField()),
                ("magnitude", models.FloatField()),
                ("color", models.CharField(max_length=7)),
                ("type", models.CharField(max_length=100)),
                ("size", models.IntegerField()),
                ("orbital_period", models.IntegerField()),
                ("temperature", models.IntegerField()),
                ("description", models.TextField()),
            ],
        ),
    ]
